import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GlobalProvider } from "@/contex/GlobalStateProvider";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body>
            {/* <main className='h-screen flex flex-col justify-center items-center'> */}
              {/* <Navbar /> */}
              {/* <GlobalProvider> */}
                {children}
                <Toaster  position="top-center" richColors />
              {/* </GlobalProvider> */}
            {/* </main> */}
          </body>
    </html>
  );
}
